#redis
FROM hyos:1.0
MAINTAINER shaoyuny yaoshaoyao@gmail.com
ENV REDIS_VERSION 5.0.6
WORKDIR /root
RUN mkdir -p /home/iotmp/base/
COPY redis-$REDIS_VERSION.tar.gz  /home/iotmp/base/
CMD ["/bin/bash"]
